name: tModLoader Stable Version Auto-Updater
on:
  schedule:
    - cron: '5 2 * * *'
jobs:
  update-tmodloader-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        path: ./
    - name: Get Current Version
      run: echo "CURRENT_VERSION=$(grep -oP '(?<=\bTMOD_VERSION=)[^;]+' ./Dockerfile)" >> $GITHUB_ENV
    - name: Print Stored Version Number
      run: echo ${{ env.CURRENT_VERSION }}
    - name: Get Repository Version
      run: echo "REPO_VERSION=$(curl -sL https://api.github.com/repos/tModLoader/tModLoader/releases | jq -r "map(select(.prerelease==false)) | first | .tag_name")" >> $GITHUB_ENV
    - name: Print Repository Version
      run: echo ${{ env.REPO_VERSION }}
    - name: Update Dockerfile Version

      if: ${{ env.CURRENT_VERSION != env.REPO_VERSION }}
      run: sed -i "s/${{ env.CURRENT_VERSION }}/${{ env.REPO_VERSION }}/" ./Dockerfile

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker image
      if: ${{ env.CURRENT_VERSION != env.REPO_VERSION }}
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: linux/arm64
        push: true
        tags: |
          ghcr.io/otomay/tmodloader1.4-arm64:${{ env.REPO_VERSION }}
          ghcr.io/otomay/tmodloader1.4-arm64:latest
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{ env.CURRENT_VERSION != env.REPO_VERSION }}
      with:
        commit_message: "Github Action: Updating to tModLoader version ${{ env.REPO_VERSION }}"
        commit_options: '--no-verify --signoff'
        repository: .
        tagging_message: '${{ env.REPO_VERSION }}'
        skip_fetch: true
        skip_checkout: true
        create_branch: false
      
